/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_kw_env = 1,
  sym_kw_default_env = 2,
  sym_file_key = 3,
  sym_filename = 4,
  sym_kw_task = 5,
  sym_command = 6,
  sym_run_key = 7,
  sym_desc_key = 8,
  sym_text = 9,
  sym_alias_key = 10,
  sym_needs_key = 11,
  sym_identifier = 12,
  anon_sym_COLON = 13,
  anon_sym_EQ = 14,
  anon_sym_ = 15,
  anon_sym_SPACE = 16,
  anon_sym_COMMA = 17,
  sym_source_file = 18,
  sym__definition = 19,
  sym__env_definition = 20,
  sym_env = 21,
  sym_default_env = 22,
  sym_file_definition = 23,
  sym_task = 24,
  sym_run_definition = 25,
  sym_desc_definition = 26,
  sym_alias_definition = 27,
  sym_needs_definition = 28,
  sym__colon = 29,
  sym__equals = 30,
  sym__indent = 31,
  sym__space = 32,
  sym_list = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_task_repeat1 = 35,
  aux_sym_list_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_kw_env] = "kw_env",
  [sym_kw_default_env] = "kw_default_env",
  [sym_file_key] = "file_key",
  [sym_filename] = "filename",
  [sym_kw_task] = "kw_task",
  [sym_command] = "command",
  [sym_run_key] = "run_key",
  [sym_desc_key] = "desc_key",
  [sym_text] = "text",
  [sym_alias_key] = "alias_key",
  [sym_needs_key] = "needs_key",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_] = "  ",
  [anon_sym_SPACE] = " ",
  [anon_sym_COMMA] = ",",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__env_definition] = "_env_definition",
  [sym_env] = "env",
  [sym_default_env] = "default_env",
  [sym_file_definition] = "file_definition",
  [sym_task] = "task",
  [sym_run_definition] = "run_definition",
  [sym_desc_definition] = "desc_definition",
  [sym_alias_definition] = "alias_definition",
  [sym_needs_definition] = "needs_definition",
  [sym__colon] = "_colon",
  [sym__equals] = "_equals",
  [sym__indent] = "_indent",
  [sym__space] = "_space",
  [sym_list] = "list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_task_repeat1] = "task_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_kw_env] = sym_kw_env,
  [sym_kw_default_env] = sym_kw_default_env,
  [sym_file_key] = sym_file_key,
  [sym_filename] = sym_filename,
  [sym_kw_task] = sym_kw_task,
  [sym_command] = sym_command,
  [sym_run_key] = sym_run_key,
  [sym_desc_key] = sym_desc_key,
  [sym_text] = sym_text,
  [sym_alias_key] = sym_alias_key,
  [sym_needs_key] = sym_needs_key,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_] = anon_sym_,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__env_definition] = sym__env_definition,
  [sym_env] = sym_env,
  [sym_default_env] = sym_default_env,
  [sym_file_definition] = sym_file_definition,
  [sym_task] = sym_task,
  [sym_run_definition] = sym_run_definition,
  [sym_desc_definition] = sym_desc_definition,
  [sym_alias_definition] = sym_alias_definition,
  [sym_needs_definition] = sym_needs_definition,
  [sym__colon] = sym__colon,
  [sym__equals] = sym__equals,
  [sym__indent] = sym__indent,
  [sym__space] = sym__space,
  [sym_list] = sym_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_task_repeat1] = aux_sym_task_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_kw_env] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_default_env] = {
    .visible = true,
    .named = true,
  },
  [sym_file_key] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_task] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_run_key] = {
    .visible = true,
    .named = true,
  },
  [sym_desc_key] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_key] = {
    .visible = true,
    .named = true,
  },
  [sym_needs_key] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__env_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_env] = {
    .visible = true,
    .named = true,
  },
  [sym_default_env] = {
    .visible = true,
    .named = true,
  },
  [sym_file_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_run_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_desc_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_needs_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__colon] = {
    .visible = false,
    .named = true,
  },
  [sym__equals] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_task_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        ',', 59,
        ':', 55,
        '=', 56,
        'a', 24,
        'd', 12,
        'e', 26,
        'f', 20,
        'n', 16,
        'r', 33,
        't', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == ',') ADVANCE(59);
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(57);
      if (lookahead == ',') ADVANCE(59);
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(8);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(8);
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(45);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(52);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 35:
      if (lookahead == 'v') ADVANCE(41);
      END_STATE();
    case 36:
      if (lookahead == 'v') ADVANCE(42);
      END_STATE();
    case 37:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 38:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (lookahead == '.' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == ',') ADVANCE(59);
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_kw_env);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_kw_default_env);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_file_key);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == '.' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_kw_task);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_command);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_run_key);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_desc_key);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_alias_key);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_needs_key);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 39},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 39},
  [7] = {.lex_state = 39},
  [8] = {.lex_state = 39},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 39},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 39},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 39},
  [20] = {.lex_state = 39},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 37},
  [35] = {.lex_state = 37},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 37},
  [42] = {.lex_state = 37},
  [43] = {.lex_state = 37},
  [44] = {.lex_state = 38},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 37},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_kw_env] = ACTIONS(1),
    [sym_kw_default_env] = ACTIONS(1),
    [sym_file_key] = ACTIONS(1),
    [sym_kw_task] = ACTIONS(1),
    [sym_run_key] = ACTIONS(1),
    [sym_desc_key] = ACTIONS(1),
    [sym_alias_key] = ACTIONS(1),
    [sym_needs_key] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__definition] = STATE(5),
    [sym__env_definition] = STATE(5),
    [sym_env] = STATE(5),
    [sym_default_env] = STATE(5),
    [sym_task] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_kw_env] = ACTIONS(5),
    [sym_kw_default_env] = ACTIONS(7),
    [sym_kw_task] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_,
    STATE(16), 1,
      sym__indent,
    ACTIONS(13), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
    STATE(2), 5,
      sym_run_definition,
      sym_desc_definition,
      sym_alias_definition,
      sym_needs_definition,
      aux_sym_task_repeat1,
  [22] = 5,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    ACTIONS(22), 1,
      anon_sym_,
    STATE(16), 1,
      sym__indent,
    ACTIONS(20), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
    STATE(2), 5,
      sym_run_definition,
      sym_desc_definition,
      sym_alias_definition,
      sym_needs_definition,
      aux_sym_task_repeat1,
  [44] = 5,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      sym_kw_env,
    ACTIONS(29), 1,
      sym_kw_default_env,
    ACTIONS(32), 1,
      sym_kw_task,
    STATE(4), 6,
      sym__definition,
      sym__env_definition,
      sym_env,
      sym_default_env,
      sym_task,
      aux_sym_source_file_repeat1,
  [65] = 5,
    ACTIONS(5), 1,
      sym_kw_env,
    ACTIONS(7), 1,
      sym_kw_default_env,
    ACTIONS(9), 1,
      sym_kw_task,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(4), 6,
      sym__definition,
      sym__env_definition,
      sym_env,
      sym_default_env,
      sym_task,
      aux_sym_source_file_repeat1,
  [86] = 4,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    STATE(6), 1,
      aux_sym_list_repeat1,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(39), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [102] = 3,
    ACTIONS(22), 1,
      anon_sym_,
    STATE(16), 1,
      sym__indent,
    STATE(3), 5,
      sym_run_definition,
      sym_desc_definition,
      sym_alias_definition,
      sym_needs_definition,
      aux_sym_task_repeat1,
  [116] = 4,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    STATE(6), 1,
      aux_sym_list_repeat1,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(46), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [132] = 4,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    STATE(8), 1,
      aux_sym_list_repeat1,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(52), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [148] = 2,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(39), 4,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
      anon_sym_COMMA,
  [159] = 2,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(56), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [169] = 2,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(60), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [179] = 2,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(64), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [189] = 2,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(68), 3,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [199] = 1,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [206] = 4,
    ACTIONS(72), 1,
      sym_run_key,
    ACTIONS(74), 1,
      sym_desc_key,
    ACTIONS(76), 1,
      sym_alias_key,
    ACTIONS(78), 1,
      sym_needs_key,
  [219] = 1,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [226] = 1,
    ACTIONS(82), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default_env,
      sym_kw_task,
  [233] = 3,
    ACTIONS(84), 1,
      anon_sym_,
    STATE(15), 1,
      sym_file_definition,
    STATE(48), 1,
      sym__indent,
  [243] = 3,
    ACTIONS(84), 1,
      anon_sym_,
    STATE(17), 1,
      sym_file_definition,
    STATE(48), 1,
      sym__indent,
  [253] = 2,
    ACTIONS(86), 1,
      anon_sym_SPACE,
    STATE(29), 1,
      sym__space,
  [260] = 2,
    ACTIONS(88), 1,
      anon_sym_SPACE,
    STATE(35), 1,
      sym__space,
  [267] = 2,
    ACTIONS(90), 1,
      anon_sym_SPACE,
    STATE(46), 1,
      sym__space,
  [274] = 2,
    ACTIONS(92), 1,
      anon_sym_SPACE,
    STATE(49), 1,
      sym__space,
  [281] = 2,
    ACTIONS(94), 1,
      anon_sym_EQ,
    STATE(30), 1,
      sym__equals,
  [288] = 2,
    ACTIONS(96), 1,
      anon_sym_EQ,
    STATE(24), 1,
      sym__equals,
  [295] = 2,
    ACTIONS(98), 1,
      anon_sym_EQ,
    STATE(23), 1,
      sym__equals,
  [302] = 2,
    ACTIONS(100), 1,
      anon_sym_EQ,
    STATE(31), 1,
      sym__equals,
  [309] = 2,
    ACTIONS(102), 1,
      anon_sym_EQ,
    STATE(22), 1,
      sym__equals,
  [316] = 2,
    ACTIONS(104), 1,
      anon_sym_SPACE,
    STATE(44), 1,
      sym__space,
  [323] = 2,
    ACTIONS(106), 1,
      anon_sym_SPACE,
    STATE(34), 1,
      sym__space,
  [330] = 2,
    ACTIONS(108), 1,
      anon_sym_SPACE,
    STATE(27), 1,
      sym__space,
  [337] = 2,
    ACTIONS(110), 1,
      anon_sym_COLON,
    STATE(19), 1,
      sym__colon,
  [344] = 2,
    ACTIONS(112), 1,
      sym_identifier,
    STATE(12), 1,
      sym_list,
  [351] = 2,
    ACTIONS(112), 1,
      sym_identifier,
    STATE(13), 1,
      sym_list,
  [358] = 2,
    ACTIONS(114), 1,
      anon_sym_COLON,
    STATE(20), 1,
      sym__colon,
  [365] = 2,
    ACTIONS(116), 1,
      anon_sym_SPACE,
    STATE(26), 1,
      sym__space,
  [372] = 2,
    ACTIONS(118), 1,
      anon_sym_SPACE,
    STATE(25), 1,
      sym__space,
  [379] = 2,
    ACTIONS(120), 1,
      anon_sym_COLON,
    STATE(7), 1,
      sym__colon,
  [386] = 2,
    ACTIONS(122), 1,
      anon_sym_SPACE,
    STATE(28), 1,
      sym__space,
  [393] = 1,
    ACTIONS(124), 1,
      sym_identifier,
  [397] = 1,
    ACTIONS(126), 1,
      sym_identifier,
  [401] = 1,
    ACTIONS(128), 1,
      sym_identifier,
  [405] = 1,
    ACTIONS(130), 1,
      sym_filename,
  [409] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [413] = 1,
    ACTIONS(134), 1,
      sym_text,
  [417] = 1,
    ACTIONS(136), 1,
      sym_identifier,
  [421] = 1,
    ACTIONS(138), 1,
      sym_file_key,
  [425] = 1,
    ACTIONS(140), 1,
      sym_command,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 65,
  [SMALL_STATE(6)] = 86,
  [SMALL_STATE(7)] = 102,
  [SMALL_STATE(8)] = 116,
  [SMALL_STATE(9)] = 132,
  [SMALL_STATE(10)] = 148,
  [SMALL_STATE(11)] = 159,
  [SMALL_STATE(12)] = 169,
  [SMALL_STATE(13)] = 179,
  [SMALL_STATE(14)] = 189,
  [SMALL_STATE(15)] = 199,
  [SMALL_STATE(16)] = 206,
  [SMALL_STATE(17)] = 219,
  [SMALL_STATE(18)] = 226,
  [SMALL_STATE(19)] = 233,
  [SMALL_STATE(20)] = 243,
  [SMALL_STATE(21)] = 253,
  [SMALL_STATE(22)] = 260,
  [SMALL_STATE(23)] = 267,
  [SMALL_STATE(24)] = 274,
  [SMALL_STATE(25)] = 281,
  [SMALL_STATE(26)] = 288,
  [SMALL_STATE(27)] = 295,
  [SMALL_STATE(28)] = 302,
  [SMALL_STATE(29)] = 309,
  [SMALL_STATE(30)] = 316,
  [SMALL_STATE(31)] = 323,
  [SMALL_STATE(32)] = 330,
  [SMALL_STATE(33)] = 337,
  [SMALL_STATE(34)] = 344,
  [SMALL_STATE(35)] = 351,
  [SMALL_STATE(36)] = 358,
  [SMALL_STATE(37)] = 365,
  [SMALL_STATE(38)] = 372,
  [SMALL_STATE(39)] = 379,
  [SMALL_STATE(40)] = 386,
  [SMALL_STATE(41)] = 393,
  [SMALL_STATE(42)] = 397,
  [SMALL_STATE(43)] = 401,
  [SMALL_STATE(44)] = 405,
  [SMALL_STATE(45)] = 409,
  [SMALL_STATE(46)] = 413,
  [SMALL_STATE(47)] = 417,
  [SMALL_STATE(48)] = 421,
  [SMALL_STATE(49)] = 425,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 4, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 4, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_definition, 6, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_run_definition, 6, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_definition, 6, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_definition, 6, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_needs_definition, 6, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_needs_definition, 6, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_desc_definition, 6, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_desc_definition, 6, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_env, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_definition, 6, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [132] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_taskr(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "taskr",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
