/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 93
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 1
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_kw_env = 1,
  sym_kw_default = 2,
  sym_file_key = 3,
  sym_filename = 4,
  sym_kw_task = 5,
  sym_run_key = 6,
  sym_desc_key = 7,
  sym_alias_key = 8,
  sym_needs_key = 9,
  sym_identifier = 10,
  anon_sym_COLON = 11,
  anon_sym_EQ = 12,
  anon_sym_ = 13,
  anon_sym_COMMA = 14,
  sym_comment = 15,
  aux_sym__command_or_text_token1 = 16,
  anon_sym_SLASH = 17,
  sym_source_file = 18,
  sym__definition = 19,
  sym__env_definition = 20,
  sym_env = 21,
  sym_default_env = 22,
  sym_file_definition = 23,
  sym_task = 24,
  sym_run_definition = 25,
  sym_desc_definition = 26,
  sym_alias_definition = 27,
  sym_needs_definition = 28,
  sym__colon = 29,
  sym__equals = 30,
  sym__indent = 31,
  sym_list = 32,
  sym__command_or_text = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_list_repeat1 = 35,
  aux_sym__command_or_text_repeat1 = 36,
  alias_sym_text = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_kw_env] = "kw_env",
  [sym_kw_default] = "kw_default",
  [sym_file_key] = "file_key",
  [sym_filename] = "filename",
  [sym_kw_task] = "kw_task",
  [sym_run_key] = "run_key",
  [sym_desc_key] = "desc_key",
  [sym_alias_key] = "alias_key",
  [sym_needs_key] = "needs_key",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_] = "  ",
  [anon_sym_COMMA] = ",",
  [sym_comment] = "comment",
  [aux_sym__command_or_text_token1] = "_command_or_text_token1",
  [anon_sym_SLASH] = "/",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__env_definition] = "_env_definition",
  [sym_env] = "env",
  [sym_default_env] = "default_env",
  [sym_file_definition] = "file_definition",
  [sym_task] = "task",
  [sym_run_definition] = "run_definition",
  [sym_desc_definition] = "desc_definition",
  [sym_alias_definition] = "alias_definition",
  [sym_needs_definition] = "needs_definition",
  [sym__colon] = "_colon",
  [sym__equals] = "_equals",
  [sym__indent] = "_indent",
  [sym_list] = "list",
  [sym__command_or_text] = "command",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym__command_or_text_repeat1] = "_command_or_text_repeat1",
  [alias_sym_text] = "text",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_kw_env] = sym_kw_env,
  [sym_kw_default] = sym_kw_default,
  [sym_file_key] = sym_file_key,
  [sym_filename] = sym_filename,
  [sym_kw_task] = sym_kw_task,
  [sym_run_key] = sym_run_key,
  [sym_desc_key] = sym_desc_key,
  [sym_alias_key] = sym_alias_key,
  [sym_needs_key] = sym_needs_key,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_] = anon_sym_,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_comment] = sym_comment,
  [aux_sym__command_or_text_token1] = aux_sym__command_or_text_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__env_definition] = sym__env_definition,
  [sym_env] = sym_env,
  [sym_default_env] = sym_default_env,
  [sym_file_definition] = sym_file_definition,
  [sym_task] = sym_task,
  [sym_run_definition] = sym_run_definition,
  [sym_desc_definition] = sym_desc_definition,
  [sym_alias_definition] = sym_alias_definition,
  [sym_needs_definition] = sym_needs_definition,
  [sym__colon] = sym__colon,
  [sym__equals] = sym__equals,
  [sym__indent] = sym__indent,
  [sym_list] = sym_list,
  [sym__command_or_text] = sym__command_or_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym__command_or_text_repeat1] = aux_sym__command_or_text_repeat1,
  [alias_sym_text] = alias_sym_text,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_kw_env] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_default] = {
    .visible = true,
    .named = true,
  },
  [sym_file_key] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_task] = {
    .visible = true,
    .named = true,
  },
  [sym_run_key] = {
    .visible = true,
    .named = true,
  },
  [sym_desc_key] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_key] = {
    .visible = true,
    .named = true,
  },
  [sym_needs_key] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__command_or_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__env_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_env] = {
    .visible = true,
    .named = true,
  },
  [sym_default_env] = {
    .visible = true,
    .named = true,
  },
  [sym_file_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_run_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_desc_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_needs_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__colon] = {
    .visible = false,
    .named = true,
  },
  [sym__equals] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__command_or_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__command_or_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_text] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [3] = alias_sym_text,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__command_or_text, 2,
    sym__command_or_text,
    alias_sym_text,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 8,
  [17] = 9,
  [18] = 14,
  [19] = 15,
  [20] = 20,
  [21] = 21,
  [22] = 13,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 21,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 29,
  [38] = 8,
  [39] = 26,
  [40] = 40,
  [41] = 27,
  [42] = 28,
  [43] = 9,
  [44] = 34,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 36,
  [49] = 34,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 58,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 70,
  [75] = 71,
  [76] = 59,
  [77] = 58,
  [78] = 61,
  [79] = 62,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 80,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(46);
      ADVANCE_MAP(
        ',', 65,
        '/', 85,
        ':', 60,
        '=', 61,
        'a', 29,
        'd', 18,
        'e', 31,
        'f', 25,
        'n', 22,
        'r', 37,
        't', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == ',') ADVANCE(65);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead == ',') ADVANCE(65);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(70);
      if (lookahead == '/') ADVANCE(85);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(69);
      if (lookahead != 0) ADVANCE(84);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(85);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(10);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0) ADVANCE(84);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(66);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(14);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 27:
      if (lookahead == 'k') ADVANCE(53);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 39:
      if (lookahead == 'v') ADVANCE(47);
      END_STATE();
    case 40:
      if (eof) ADVANCE(46);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == ',') ADVANCE(65);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(40);
      END_STATE();
    case 41:
      if (eof) ADVANCE(46);
      if (lookahead == ' ') ADVANCE(68);
      if (lookahead == '/') ADVANCE(85);
      if (lookahead == 'd') ADVANCE(74);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == 't') ADVANCE(71);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(42);
      if (('\t' <= lookahead && lookahead <= '\f')) ADVANCE(67);
      if (lookahead != 0) ADVANCE(84);
      END_STATE();
    case 42:
      if (eof) ADVANCE(46);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(42);
      END_STATE();
    case 43:
      if (eof) ADVANCE(46);
      ADVANCE_MAP(
        ',', 65,
        '/', 9,
        ':', 60,
        '=', 61,
        'a', 29,
        'd', 18,
        'e', 31,
        'f', 25,
        'n', 22,
        'r', 37,
        't', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      END_STATE();
    case 44:
      if (eof) ADVANCE(46);
      if (lookahead == '/') ADVANCE(85);
      if (lookahead == 'd') ADVANCE(74);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == 't') ADVANCE(71);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(45);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(84);
      END_STATE();
    case 45:
      if (eof) ADVANCE(46);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_kw_env);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_kw_env);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_kw_default);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_kw_default);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_file_key);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_kw_task);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_kw_task);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_run_key);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_desc_key);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_alias_key);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_needs_key);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(69);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == ' ') ADVANCE(68);
      if (lookahead == 'd') ADVANCE(74);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == 't') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(67);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == 'd') ADVANCE(74);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == 't') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(67);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == ' ') ADVANCE(70);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'a') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'a') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'd') ADVANCE(74);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead == 't') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'e') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'k') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'l') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'n') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 's') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 't') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'u') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == 'v') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym__command_or_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(66);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 40},
  [5] = {.lex_state = 40},
  [6] = {.lex_state = 40},
  [7] = {.lex_state = 40},
  [8] = {.lex_state = 41},
  [9] = {.lex_state = 41},
  [10] = {.lex_state = 40},
  [11] = {.lex_state = 40},
  [12] = {.lex_state = 40},
  [13] = {.lex_state = 40},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 44},
  [17] = {.lex_state = 44},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 40},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 40},
  [24] = {.lex_state = 40},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 40},
  [27] = {.lex_state = 40},
  [28] = {.lex_state = 40},
  [29] = {.lex_state = 40},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 40},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 40},
  [47] = {.lex_state = 40},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 40},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 40},
  [54] = {.lex_state = 40},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 11},
  [71] = {.lex_state = 11},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 11},
  [75] = {.lex_state = 11},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 11},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 11},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 11},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 11},
  [91] = {.lex_state = 12},
  [92] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_kw_env] = ACTIONS(1),
    [sym_kw_default] = ACTIONS(1),
    [sym_file_key] = ACTIONS(1),
    [sym_kw_task] = ACTIONS(1),
    [sym_run_key] = ACTIONS(1),
    [sym_desc_key] = ACTIONS(1),
    [sym_alias_key] = ACTIONS(1),
    [sym_needs_key] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(81),
    [sym__definition] = STATE(2),
    [sym__env_definition] = STATE(2),
    [sym_env] = STATE(2),
    [sym_default_env] = STATE(2),
    [sym_task] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_kw_env] = ACTIONS(7),
    [sym_kw_default] = ACTIONS(9),
    [sym_kw_task] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_kw_env,
    ACTIONS(9), 1,
      sym_kw_default,
    ACTIONS(11), 1,
      sym_kw_task,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(3), 6,
      sym__definition,
      sym__env_definition,
      sym_env,
      sym_default_env,
      sym_task,
      aux_sym_source_file_repeat1,
  [24] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_kw_env,
    ACTIONS(20), 1,
      sym_kw_default,
    ACTIONS(23), 1,
      sym_kw_task,
    STATE(3), 6,
      sym__definition,
      sym__env_definition,
      sym_env,
      sym_default_env,
      sym_task,
      aux_sym_source_file_repeat1,
  [48] = 8,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(30), 1,
      anon_sym_,
    ACTIONS(32), 1,
      sym_comment,
    STATE(5), 1,
      sym_desc_definition,
    STATE(6), 1,
      sym_alias_definition,
    STATE(7), 1,
      sym_needs_definition,
    STATE(56), 1,
      sym__indent,
    ACTIONS(28), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [75] = 7,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_,
    STATE(10), 1,
      sym_alias_definition,
    STATE(11), 1,
      sym_needs_definition,
    STATE(63), 1,
      sym__indent,
    ACTIONS(36), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [99] = 7,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      anon_sym_,
    STATE(10), 1,
      sym_desc_definition,
    STATE(12), 1,
      sym_needs_definition,
    STATE(65), 1,
      sym__indent,
    ACTIONS(36), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [123] = 7,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_,
    STATE(11), 1,
      sym_desc_definition,
    STATE(12), 1,
      sym_alias_definition,
    STATE(66), 1,
      sym__indent,
    ACTIONS(36), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [147] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym__command_or_text_repeat1,
    ACTIONS(48), 2,
      aux_sym__command_or_text_token1,
      anon_sym_SLASH,
    ACTIONS(46), 4,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
      anon_sym_,
  [167] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym__command_or_text_repeat1,
    ACTIONS(54), 2,
      aux_sym__command_or_text_token1,
      anon_sym_SLASH,
    ACTIONS(52), 4,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
      anon_sym_,
  [187] = 6,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      anon_sym_,
    STATE(45), 1,
      sym_needs_definition,
    STATE(82), 1,
      sym__indent,
    ACTIONS(59), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [208] = 6,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      anon_sym_,
    STATE(45), 1,
      sym_alias_definition,
    STATE(83), 1,
      sym__indent,
    ACTIONS(59), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [229] = 6,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_,
    STATE(45), 1,
      sym_desc_definition,
    STATE(87), 1,
      sym__indent,
    ACTIONS(59), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [250] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_list_repeat1,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(69), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [269] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_list_repeat1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(75), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [288] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_list_repeat1,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(79), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [307] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym__command_or_text_repeat1,
    ACTIONS(84), 2,
      aux_sym__command_or_text_token1,
      anon_sym_SLASH,
    ACTIONS(46), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [326] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym__command_or_text_repeat1,
    ACTIONS(86), 2,
      aux_sym__command_or_text_token1,
      anon_sym_SLASH,
    ACTIONS(52), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [345] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_list_repeat1,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [361] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_list_repeat1,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [377] = 7,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_,
    STATE(4), 1,
      sym_run_definition,
    STATE(23), 1,
      sym_desc_definition,
    STATE(24), 1,
      sym_needs_definition,
    STATE(25), 1,
      sym_alias_definition,
    STATE(33), 1,
      sym__indent,
  [399] = 3,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(79), 4,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
      anon_sym_COMMA,
  [413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      aux_sym_list_repeat1,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [429] = 6,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_,
    STATE(5), 1,
      sym_run_definition,
    STATE(46), 1,
      sym_needs_definition,
    STATE(47), 1,
      sym_alias_definition,
    STATE(50), 1,
      sym__indent,
  [448] = 6,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_,
    STATE(7), 1,
      sym_run_definition,
    STATE(32), 1,
      sym_alias_definition,
    STATE(46), 1,
      sym_desc_definition,
    STATE(52), 1,
      sym__indent,
  [467] = 6,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_,
    STATE(6), 1,
      sym_run_definition,
    STATE(32), 1,
      sym_needs_definition,
    STATE(47), 1,
      sym_desc_definition,
    STATE(55), 1,
      sym__indent,
  [486] = 3,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(104), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [499] = 3,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(108), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [512] = 3,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(112), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [525] = 3,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      anon_sym_,
    ACTIONS(116), 3,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
      anon_sym_COMMA,
  [549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [559] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_,
    STATE(12), 1,
      sym_run_definition,
    STATE(53), 1,
      sym_desc_definition,
    STATE(57), 1,
      sym__indent,
  [575] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_run_key,
    ACTIONS(124), 1,
      sym_desc_key,
    ACTIONS(126), 1,
      sym_alias_key,
    ACTIONS(128), 1,
      sym_needs_key,
  [591] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(130), 1,
      aux_sym__command_or_text_token1,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    STATE(26), 1,
      sym__command_or_text,
    STATE(38), 1,
      aux_sym__command_or_text_repeat1,
  [607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [617] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(136), 1,
      aux_sym__command_or_text_token1,
    ACTIONS(138), 1,
      anon_sym_SLASH,
    STATE(8), 1,
      aux_sym__command_or_text_repeat1,
    STATE(29), 1,
      sym__command_or_text,
  [633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [643] = 4,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_,
    STATE(43), 1,
      aux_sym__command_or_text_repeat1,
    ACTIONS(140), 2,
      aux_sym__command_or_text_token1,
      anon_sym_SLASH,
  [657] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [687] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [697] = 4,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_,
    STATE(43), 1,
      aux_sym__command_or_text_repeat1,
    ACTIONS(144), 2,
      aux_sym__command_or_text_token1,
      anon_sym_SLASH,
  [711] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(136), 1,
      aux_sym__command_or_text_token1,
    ACTIONS(138), 1,
      anon_sym_SLASH,
    STATE(8), 1,
      aux_sym__command_or_text_repeat1,
    STATE(26), 1,
      sym__command_or_text,
  [727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 4,
      ts_builtin_sym_end,
      sym_kw_env,
      sym_kw_default,
      sym_kw_task,
  [737] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_,
    STATE(11), 1,
      sym_run_definition,
    STATE(53), 1,
      sym_alias_definition,
    STATE(68), 1,
      sym__indent,
  [753] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_,
    STATE(10), 1,
      sym_run_definition,
    STATE(53), 1,
      sym_needs_definition,
    STATE(67), 1,
      sym__indent,
  [769] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(153), 1,
      aux_sym__command_or_text_token1,
    ACTIONS(155), 1,
      anon_sym_SLASH,
    STATE(16), 1,
      aux_sym__command_or_text_repeat1,
    STATE(37), 1,
      sym__command_or_text,
  [785] = 5,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(153), 1,
      aux_sym__command_or_text_token1,
    ACTIONS(155), 1,
      anon_sym_SLASH,
    STATE(16), 1,
      aux_sym__command_or_text_repeat1,
    STATE(39), 1,
      sym__command_or_text,
  [801] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_run_key,
    ACTIONS(126), 1,
      sym_alias_key,
    ACTIONS(128), 1,
      sym_needs_key,
  [814] = 4,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_,
    STATE(35), 1,
      sym_file_definition,
    STATE(89), 1,
      sym__indent,
  [827] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_run_key,
    ACTIONS(124), 1,
      sym_desc_key,
    ACTIONS(126), 1,
      sym_alias_key,
  [840] = 4,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_,
    STATE(45), 1,
      sym_run_definition,
    STATE(86), 1,
      sym__indent,
  [853] = 4,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_,
    STATE(31), 1,
      sym_file_definition,
    STATE(89), 1,
      sym__indent,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_run_key,
    ACTIONS(124), 1,
      sym_desc_key,
    ACTIONS(128), 1,
      sym_needs_key,
  [879] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_alias_key,
    ACTIONS(128), 1,
      sym_needs_key,
    ACTIONS(161), 1,
      sym_desc_key,
  [892] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_run_key,
    ACTIONS(124), 1,
      sym_desc_key,
  [902] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_EQ,
    STATE(49), 1,
      sym__equals,
  [912] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_EQ,
    STATE(36), 1,
      sym__equals,
  [922] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_EQ,
    STATE(34), 1,
      sym__equals,
  [932] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_EQ,
    STATE(70), 1,
      sym__equals,
  [942] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_EQ,
    STATE(71), 1,
      sym__equals,
  [952] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_alias_key,
    ACTIONS(128), 1,
      sym_needs_key,
  [962] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_COLON,
    STATE(51), 1,
      sym__colon,
  [972] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_needs_key,
    ACTIONS(161), 1,
      sym_desc_key,
  [982] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_alias_key,
    ACTIONS(161), 1,
      sym_desc_key,
  [992] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_run_key,
    ACTIONS(128), 1,
      sym_needs_key,
  [1002] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_run_key,
    ACTIONS(126), 1,
      sym_alias_key,
  [1012] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COLON,
    STATE(20), 1,
      sym__colon,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(27), 1,
      sym_list,
  [1032] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(28), 1,
      sym_list,
  [1042] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_COLON,
    STATE(54), 1,
      sym__colon,
  [1052] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_EQ,
    STATE(91), 1,
      sym__equals,
  [1062] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_identifier,
    STATE(41), 1,
      sym_list,
  [1072] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_identifier,
    STATE(42), 1,
      sym_list,
  [1082] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_EQ,
    STATE(48), 1,
      sym__equals,
  [1092] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_EQ,
    STATE(44), 1,
      sym__equals,
  [1102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_EQ,
    STATE(74), 1,
      sym__equals,
  [1112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_EQ,
    STATE(75), 1,
      sym__equals,
  [1122] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_identifier,
  [1129] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
  [1136] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_needs_key,
  [1143] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym_alias_key,
  [1150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_identifier,
  [1157] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_kw_env,
  [1164] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_run_key,
  [1171] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_desc_key,
  [1178] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
  [1185] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_file_key,
  [1192] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_identifier,
  [1199] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_filename,
  [1206] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 99,
  [SMALL_STATE(7)] = 123,
  [SMALL_STATE(8)] = 147,
  [SMALL_STATE(9)] = 167,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 208,
  [SMALL_STATE(12)] = 229,
  [SMALL_STATE(13)] = 250,
  [SMALL_STATE(14)] = 269,
  [SMALL_STATE(15)] = 288,
  [SMALL_STATE(16)] = 307,
  [SMALL_STATE(17)] = 326,
  [SMALL_STATE(18)] = 345,
  [SMALL_STATE(19)] = 361,
  [SMALL_STATE(20)] = 377,
  [SMALL_STATE(21)] = 399,
  [SMALL_STATE(22)] = 413,
  [SMALL_STATE(23)] = 429,
  [SMALL_STATE(24)] = 448,
  [SMALL_STATE(25)] = 467,
  [SMALL_STATE(26)] = 486,
  [SMALL_STATE(27)] = 499,
  [SMALL_STATE(28)] = 512,
  [SMALL_STATE(29)] = 525,
  [SMALL_STATE(30)] = 538,
  [SMALL_STATE(31)] = 549,
  [SMALL_STATE(32)] = 559,
  [SMALL_STATE(33)] = 575,
  [SMALL_STATE(34)] = 591,
  [SMALL_STATE(35)] = 607,
  [SMALL_STATE(36)] = 617,
  [SMALL_STATE(37)] = 633,
  [SMALL_STATE(38)] = 643,
  [SMALL_STATE(39)] = 657,
  [SMALL_STATE(40)] = 667,
  [SMALL_STATE(41)] = 677,
  [SMALL_STATE(42)] = 687,
  [SMALL_STATE(43)] = 697,
  [SMALL_STATE(44)] = 711,
  [SMALL_STATE(45)] = 727,
  [SMALL_STATE(46)] = 737,
  [SMALL_STATE(47)] = 753,
  [SMALL_STATE(48)] = 769,
  [SMALL_STATE(49)] = 785,
  [SMALL_STATE(50)] = 801,
  [SMALL_STATE(51)] = 814,
  [SMALL_STATE(52)] = 827,
  [SMALL_STATE(53)] = 840,
  [SMALL_STATE(54)] = 853,
  [SMALL_STATE(55)] = 866,
  [SMALL_STATE(56)] = 879,
  [SMALL_STATE(57)] = 892,
  [SMALL_STATE(58)] = 902,
  [SMALL_STATE(59)] = 912,
  [SMALL_STATE(60)] = 922,
  [SMALL_STATE(61)] = 932,
  [SMALL_STATE(62)] = 942,
  [SMALL_STATE(63)] = 952,
  [SMALL_STATE(64)] = 962,
  [SMALL_STATE(65)] = 972,
  [SMALL_STATE(66)] = 982,
  [SMALL_STATE(67)] = 992,
  [SMALL_STATE(68)] = 1002,
  [SMALL_STATE(69)] = 1012,
  [SMALL_STATE(70)] = 1022,
  [SMALL_STATE(71)] = 1032,
  [SMALL_STATE(72)] = 1042,
  [SMALL_STATE(73)] = 1052,
  [SMALL_STATE(74)] = 1062,
  [SMALL_STATE(75)] = 1072,
  [SMALL_STATE(76)] = 1082,
  [SMALL_STATE(77)] = 1092,
  [SMALL_STATE(78)] = 1102,
  [SMALL_STATE(79)] = 1112,
  [SMALL_STATE(80)] = 1122,
  [SMALL_STATE(81)] = 1129,
  [SMALL_STATE(82)] = 1136,
  [SMALL_STATE(83)] = 1143,
  [SMALL_STATE(84)] = 1150,
  [SMALL_STATE(85)] = 1157,
  [SMALL_STATE(86)] = 1164,
  [SMALL_STATE(87)] = 1171,
  [SMALL_STATE(88)] = 1178,
  [SMALL_STATE(89)] = 1185,
  [SMALL_STATE(90)] = 1192,
  [SMALL_STATE(91)] = 1199,
  [SMALL_STATE(92)] = 1206,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 4, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 4, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 5, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 5, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_or_text, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_or_text, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__command_or_text_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__command_or_text_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__command_or_text_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 6, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 6, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__command_or_text_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_desc_definition, 4, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_desc_definition, 4, 0, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_definition, 4, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_definition, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_needs_definition, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_needs_definition, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_definition, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_run_definition, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_env, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_definition, 4, 0, 0),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__command_or_text_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 7, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [195] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_taskr(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "taskr",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
